docker-build:
  image: docker:cli
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE_NAME: "$CI_REGISTRY_IMAGE:latest"
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

  script:
    - docker build --pull -t "$DOCKER_IMAGE_NAME" .
    - docker push "$DOCKER_IMAGE_NAME"

  rules:
    # Run only if the commit is on the default branch (e.g., main)
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      exists: [Dockerfile]
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'
      exists: [Dockerfile]
