docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - |
      # Detect which tag to use for the image
      if [[ -n "$CI_COMMIT_TAG" ]]; then
        export DOCKER_IMAGE_NAME="$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
      elif [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        export DOCKER_IMAGE_NAME="$CI_REGISTRY_IMAGE:latest"
      else
        echo "Not a tag or default branch. Skipping image build."
        exit 0
      fi
      echo "Docker image to build: $DOCKER_IMAGE_NAME"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

  script:
    - docker build --pull -t "$DOCKER_IMAGE_NAME" .
    - docker push "$DOCKER_IMAGE_NAME"

  rules:
    # Only run when pushing to main branch (default) or pushing a semantic version tag
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      exists: [Dockerfile]
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'
      exists: [Dockerfile]


docker-push-hub:
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  needs:
    - job: docker-build-tag
      optional: true
  before_script:
    # Login to Docker Hub
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
    # Login to GitLab Registry
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    # 1. Pull desde GitLab Container Registry
    - docker pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"

    # 2. Local tag for docker
    - docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" "$DOCKER_HUB_USER/oauth2-passport-server:$CI_COMMIT_TAG"

    # 3. Push a Docker Hub
    - docker push "$DOCKER_HUB_USER/oauth2-passport-server:$CI_COMMIT_TAG"
  only:
    - tags

