docker-build:
  image: docker:cli
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE_TAG: ${CI_COMMIT_TAG:-${CI_COMMIT_REF_SLUG:-temp}}
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$DOCKER_IMAGE_TAG
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$DOCKER_IMAGE_NAME" .
    - docker push "$DOCKER_IMAGE_NAME"
    - |
        if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
            docker tag "$DOCKER_IMAGE_NAME" "$CI_REGISTRY_IMAGE:latest"
            docker push "$CI_REGISTRY_IMAGE:latest"
        fi
  rules:
    - if: $CI_COMMIT_BRANCH
      exists: [Dockerfile]
    - if: $CI_COMMIT_TAG
      exists: [Dockerfile]
