docker-build:
  image: docker:cli
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE_TAG: ""
    DOCKER_IMAGE_NAME: ""
  before_script:
    - |
      if [[ -n "$CI_COMMIT_TAG" ]]; then
        export DOCKER_IMAGE_TAG="$CI_COMMIT_TAG"
      elif [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        export DOCKER_IMAGE_TAG="$CI_COMMIT_REF_SLUG"
      fi
      export DOCKER_IMAGE_NAME="$CI_REGISTRY_IMAGE:$DOCKER_IMAGE_TAG"
      echo "Docker image to build: $DOCKER_IMAGE_NAME"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

  script:
    - docker build --pull -t "$DOCKER_IMAGE_NAME" .
    - docker push "$DOCKER_IMAGE_NAME"
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        docker tag "$DOCKER_IMAGE_NAME" "$CI_REGISTRY_IMAGE:latest"
        docker push "$CI_REGISTRY_IMAGE:latest"
      fi

  rules:
    # Solo construye imagen si estás en main...
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      exists: [Dockerfile]
    # ... o si es un push por tag (v1.0.0, etc.)
    - if: $CI_COMMIT_TAG
      exists: [Dockerfile]
