docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - |
      # Detect which tag to use for the image
      if [[ -n "$CI_COMMIT_TAG" ]]; then
        export DOCKER_IMAGE_NAME="$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
      else
        export DOCKER_IMAGE_NAME="$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
      fi
      echo "Docker image to build: $DOCKER_IMAGE_NAME"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build --pull -t "$DOCKER_IMAGE_NAME" .
    - docker push "$DOCKER_IMAGE_NAME"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      exists: [Dockerfile]

docker-push-hub:
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  needs:
    - job: docker-build
      artifacts: false
  before_script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    - docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" "$DOCKER_HUB_USER/oauth2-passport-server:$CI_COMMIT_REF_SLUG"
    - docker push "$DOCKER_HUB_USER/oauth2-passport-server:$CI_COMMIT_REF_SLUG"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      exists: [Dockerfile]