name: oauth2-server

services:
    db:
        image: postgres:17
        restart: always
        volumes:
            - pg-data:/var/lib/postgresql/data
        env_file:
            - .env
        environment:
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
            POSTGRES_DB: "${DB_DATABASE}"
        networks:
            - internal-net
        healthcheck:
            test: [ "CMD", "pg_isready", "-U", "${DB_USERNAME}" ]
            interval: 10s
            timeout: 10s
            retries: 10

    adminer:
        image: adminer:latest
        restart: always
        ports:
            - "8002:8080"
        depends_on:
            db:
                condition: service_healthy
        environment:
            ADMINER_DEFAULT_SERVER: db
        networks:
            - internal-net
            - public-net

    app:
        image: elyerr/oauth2-passport-server:v2.0.1
        restart: always
        ports:
            - "8005:80"
            - "25:25"
            - "587:587"
            - "465:465"
        depends_on:
            db:
                condition: service_healthy
        volumes:
            - .env:/var/www/.env
            - app-secrets:/var/www/secrets
        command: sh -c "/usr/local/bin/laravel-scripts.sh"
        networks:
            - internal-net
            - public-net

volumes:
    pg-data:
    app-secrets:

networks:
    internal-net:
        internal: true
    public-net:
        driver: bridge
